select
    cast(id as int64) as laptop_model_id,
    cast(name as string) as laptop_name,
    cast(brand_id as int64) as brand_id,
    cast(cpu_model_id as int64) as cpu_model_id,
    cast(gpu_model_id as int64) as gpu_model_id,
    cast(is_gaming_laptop as boolean) as is_gaming_laptop,
    cast(is_workstation as boolean) as is_workstation,
    cast(is_mobile_device as boolean) as is_mobile_device,
    cast(is_visible as boolean) as is_visible,
    cast(is_active as boolean) as is_active,
    cast(year_introduce as int64) as year_introduce,
    cast(cpu_note as string) as cpu_note,
    cast(cpu_tdp as string) as cpu_tdp,
    cast(gpu_note as string) as gpu_note,
    cast(gpu_tdp as string) as gpu_tdp,
    cast(battery_capacity_whr as float64) as battery_capacity_whr,
    cast(screen_size as float64) as screen_size,
    cast(screen_dimension_width as float64) as screen_dimension_width,
    cast(screen_dimension_height as float64) as screen_dimension_height,
    cast(screen_ppi as float64) as screen_ppi,
    cast(laptop_weight as float64) as laptop_weight,
    cast(charger_weight as float64) as charger_weight,
    cast(brand_model_codename as string) as brand_model_codename,
    cast(thumbnail_image_url as string) as thumbnail_image_url,
    timestamp_seconds(cast(created_on / 1000000000 as int64)) as created_on,
    timestamp_seconds(cast(changed_on / 1000000000 as int64)) as changed_on,
    timestamp_seconds(cast(elton_created_at / 1000000000 as int64)) as elton_created_at
from {{ source('laplaptech_raw', 'raw_laptop_model') }}
